name: pgdev
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - pgcore >= 1.5.0
  - matplotlib
  - jupyter
  - sphinx >= 3.1
  - pytest
  - numpy
  - scipy
  - pytest-cov
  - pytest-html
  - sphinx-gallery
  - sphinxcontrib-bibtex
  - sphinxcontrib-programoutput
  - sphinxcontrib-spelling
  - sphinxcontrib-doxylink
  - bibtexparser
  - pyvista[all,trame]>=0.42
  - meshio
  - scooby
  - sphinx-design
  - pydata-sphinx-theme
  - myst-parser
  - myst-nb
  - jupytext
